version: '3.8'
services:
  python-ocr:
    build:
      context: .
      dockerfile: apps/python-ocr/Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    ports:
      - '8000:8000'
    volumes:
      - ./apps/python-ocr:/app
    command:
      ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000', '--reload']

  postgres:
    image: postgres:latest
    container_name: resume_analyze_db_dev
    environment:
      POSTGRES_USER: ${DB_USER:-resume_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-resume_secure_pass_2024}
      POSTGRES_DB: ${DB_NAME:-resume_analyze_db}
    ports:
      - '${DB_PORT:-5531}:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
