version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: apps/nest-api/Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      - python-ocr
      - postgres
    networks:
      - database-network

  python-ocr:
    build:
      context: .
      dockerfile: apps/python-ocr/Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - '8000:8000'

  postgres:
    image: postgres:latest
    container_name: resume_analyze_db
    environment:
      POSTGRES_USER: ${DB_USER:-resume_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-resume_secure_pass_2024}
      POSTGRES_DB: ${DB_NAME:-resume_analyze_db}
    ports:
      - '${DB_PORT:-5531}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database-network # Add this

volumes:
  postgres_data:

networks:
  database-network:
    driver: bridge
